version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: npm run start:dev