version: '3.8'

services:
  main:
    build:
      context: .
      target: development
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
    command: npm run start:debug
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.6
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: